export const ActionTypes = {
    SET_MOVIES : "SET_MOVIES",
    SELECTED_MOVIE : "SELECTED_MOVIE",
    REMOVE_SELECTED_MOVIE : "REMOVE_SELECTED_MOVIE",

    SET_TANDAS : "SET_TANDAS",
    SELECTED_TANDA : "SET_TANDA",
    REMOVE_SELECTED_TANDA : "REMOVE_SELECT_TANDA",

    SET_USER : "SET_USER",
    REMOVE_USER : "REMOVE_USER",
    
    SET_FOODS : "SET_FOODS",
    SELECT_FOOD : "SELECT_FOOD",
    REMOVE_SELECTED_FOOD : "SELECT_FOOD",
};