export const ActionTypes = {
    SET_MOVIES : "SET_MOVIES",
    SELECTED_MOVIE : "SELECTED_MOVIE",
    REMOVE_SELECTED_MOVIE : "REMOVE_SELECTED_MOVIE",



    SET_FOODS : "SET_FOODS",
    SELECTED_FOOD : "SELECTED_FOOD",
    REMOVE_SELECTED_FOOD : "REMOVE_SELECTED_FOOD"
};